name: Build And Deploy
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install And Build
        run: |
          npm install pnpm -g
          pnpm install --filter 'webview-vue'
          pnpm run --filter 'webview-vue' build
        
      - name: Show build output
        run: ls -R

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with: 
          BRANCH: release/web-generate-code
          FOLDER: dist/webview-vue
          TOKEN: ${{ secrets.GENERATE_TOKEN }}
